{% set name = "aeon" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aeon-{{ version }}.tar.gz
  sha256: a03147e3fbe7385d607c3203ce1e2b3d6a3f2093d19f6e093fdde17e7eb01425

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >61
    - toml
    - python-build
    - pip
    - wheel
  run:
    - python >={{ python_min }}
    - deprecated >=1.2.13
    - numba >=0.55,<0.61.0
    - numpy >=1.21.0,<2.1.0
    - packaging >=20.0
    - pandas >=2.0.0,<2.3.0
    - scikit-learn >=1.0.0,<1.6.0
    - scipy >=1.9.0,<1.15.0
    - typing_extensions >=4.6.0

test:
  imports:
    - aeon
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aeon-toolkit.org/
  dev_url: https://github.com/aeon-toolkit/
  doc_url: https://aeon-toolkit.org/
  summary: A unified framework for machine learning with time series
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MatthewMiddlehurst
    - thewchan
