{% set name = "aeon" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aeon-{{ version }}.tar.gz
  sha256: 87c181acc4845befc1c0fcc209da6af5f7d7592c2eab524ff459b2789b823f95

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - setuptools >61
    - toml
    - python-build
    - pip
    - wheel
  run:
    - python >=3.9,<3.13
    - deprecated >=1.2.13
    - numba >=0.55,<0.61.0
    - numpy >=1.21.0,<2.1.0
    - packaging >=20.0
    - pandas >=2.0.0,<2.3.0
    - scikit-learn >=1.0.0,<1.6.0
    - scipy >=1.9.0,<1.15.0
    - typing_extensions >=4.6.0

test:
  imports:
    - aeon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aeon-toolkit.org/
  dev_url: https://github.com/aeon-toolkit/
  doc_url: https://aeon-toolkit.org/
  summary: A unified framework for machine learning with time series
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MatthewMiddlehurst
    - thewchan
