{% set name = "aeon" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aeon-{{ version }}.tar.gz
  sha256: fe9821c30bcb1ed628c9b41e702173a4e3e4bca6fc604b6a2a7f545b6e773d81

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - setuptools >61
    - toml
    - python-build
    - pip
  run:
    - python >=3.8,<3.13
    - deprecated >=1.2.13
    - numba >=0.55,<0.60.0
    - numpy >=1.21.0,<1.27.0
    - packaging >=20.0
    - pandas >=1.5.3,<2.1.0
    - scikit-learn >=1.0.0,<1.5.0
    - scipy >=1.2.0,<1.13.0

test:
  imports:
    - aeon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aeon-toolkit.org/
  dev_url: https://github.com/aeon-toolkit/
  doc_url: https://aeon-toolkit.org/
  summary: A unified framework for machine learning with time series
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MatthewMiddlehurst
    - thewchan
